title: Thomas Walker
description: Hello, I am an undergraduate mathematics student currently studying at Imperial College London.
logo: /assets/profile_img.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
