title: Thomas Walker
description: Imperial College London - BSc Mathematics.
logo: /assets/picture_newtons_apple_tree.jpg
#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: broccolini/swiss
theme_color: black
plugins:
- jekyll-remote-theme
